/// Flutter icons ReFreezerIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReFreezerIcons
///      fonts:
///       - asset: fonts/ReFreezerIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class ReFreezerIcons {
  ReFreezerIcons._();

  static const _kFontFam = 'ReFreezerIcons';
  static const String? _kFontPkg = null;

  static const IconData lyrics_mic = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crowdin = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
